version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${ADMIN_EMAIL}
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    image: http-knockd:latest
    build: .
    environment:
      REDIS_HOST: "redis"
      LETSENCRYPT_HOST: "${HOSTNAME}"
      TIMEOUT: "${TIMEOUT}"
      VIRTUAL_HOST: "${HOSTNAME}"
      VIRTUAL_PORT: 8000
    depends_on:
      - redis
    volumes:
      - ./db:/app/db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

